# Generated by Django 5.1.2 on 2024-11-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_userprogress_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='reset',
            field=models.BooleanField(default=False),
        ),
    ]
